version: '3.8'
services:
  api:
    build:
      context: .
    command: npx nx serve api
    ports:
      - "3001:3000"

  dashboard:
    build:
      context: .
    command: npx nx serve dashboard --host=0.0.0.0
    ports:
      - "4200:4200"
